spring.datasource.url=jdbc:tc:mysql:8.0.33:///testdb
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

# If you use DDL scripts or need Spring Data JDBC to initialize schemas:
spring.sql.init.mode=always